# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_task.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'grpc_task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgrpc_task.proto\x12\tgrpc_task\"]\n\x0bTaskRequest\x12\x11\n\ttask_name\x18\x01 \x01(\t\x12\x12\n\ninput_data\x18\x02 \x01(\t\x12\x14\n\x0c\x66ile_content\x18\x03 \x01(\x0c\x12\x11\n\tfile_name\x18\x04 \x01(\t\"B\n\x0cTaskResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x12\n\noutput_url\x18\x03 \x01(\t2P\n\x0bTaskService\x12\x41\n\nSubmitTask\x12\x16.grpc_task.TaskRequest\x1a\x17.grpc_task.TaskResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKREQUEST']._serialized_start=30
  _globals['_TASKREQUEST']._serialized_end=123
  _globals['_TASKRESPONSE']._serialized_start=125
  _globals['_TASKRESPONSE']._serialized_end=191
  _globals['_TASKSERVICE']._serialized_start=193
  _globals['_TASKSERVICE']._serialized_end=273
# @@protoc_insertion_point(module_scope)
